Image with rollovers
hlxsites/uhg-surest pull request #34
Opened 2023-03-03 22:23 UTC by badvision

Fix #15 

Test URLs:
- Before: new feature
- After: https://image-with-rollovers--uhg-surest--hlxsites.hlx.page/

2023-03-05 05:30 UTC, shsteimer requested changes

2023-03-05 05:30 UTC, shsteimer commented on styles/styles.css
> +.block.images {
sorry if this wasn't clear, but I think we should create an images block for this.

2023-03-05 05:30 UTC, shsteimer commented on styles/styles.css
> +  flex-flow: row nowrap;
on mobile, the images get awfully small. probably do flex direction column and then switch it at table breakpoint?

2023-03-05 05:30 UTC, shsteimer commented on styles/styles.css
> +.block.images .icon {
I think we probably want to change this so these are images in the word doc so it's easy for authors to update. this is fine for now and we can revisit when time allows later, but just making a note of it.

2023-03-06 14:42 UTC, badvision commented on styles/styles.css
> +  flex-flow: row nowrap;
I thought so too, oddly their website shows small images on desktop, but makes the images bigger on mobile.  I'll adjust it, no problem.

2023-03-06 14:43 UTC, badvision commented on styles/styles.css
> +.block.images .icon {
Both cases work in this PR.  The second image is a PNG image in the original and the rest are SVG currently.  If we change the word doc this should "just work."

2023-03-06 22:26 UTC, merged