Blog post
hlxsites/uhg-surest pull request #45
Opened 2023-03-07 20:03 UTC by qilto

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #16

Test URLs:
- Before: https://main--uhg-surest--hlxsites.hlx.page/blog/what-is-health-equity
- After: https://blog-post--uhg-surest--hlxsites.hlx.page/blog/what-is-health-equity

2023-03-07 20:09 UTC, shsteimer commented on blocks/hero/hero.js
> +    if (document.querySelector('meta[name="template"][content="Blog Post"]')) {
you can just use lib-franklin getMetadata() for this?

2023-03-07 20:10 UTC, shsteimer commented on blocks/hero/hero.js
> +function decorateBlogHeader(block) {
I kinda don't think I want all of this stuff mixed up in the hero. Lets chat and figure out the best way to do this

2023-03-07 20:56 UTC, badvision requested changes
Same questions/concerns as @shsteimer

2023-03-07 20:56 UTC, badvision commented on blocks/hero/hero.js
> +function decorateBlogHeader(block) {
I agree -- we really want the blog stuff to be in its own file somehow.  Does franklin understand component-theme.css or component-template.css variations?

2023-03-08 19:58 UTC, qilto commented on blocks/hero/hero.js
> +function decorateBlogHeader(block) {
@badvision We decided to leave this with hero for now, but will probably separate it out later.

2023-03-08 22:49 UTC, merged